version: '3'
services:
  postgres-sql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    ports:
      - 5433:5432

  books-service:
    image: jaimesalvador/examen:1.0.0
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://postgres-sql:5432/distribuida
    depends_on:
      - postgres-sql
    deploy:
      replicas: 1
    ports:
      - 7001:7001